# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cIVwp8i6caxe3WAPyqnRbcSFvjU3GCkQ4EDoagyWY7WPg30B5fFSFlXLATEB5lAtP/nxCuaW5WF0dF3lCWNjtRSPSQ7SClBdFQJjbbsD0t2P+xCC/c0G2duMdG8nqz1DgrksZXrilnwaGEsQ9y+4OEWYlqFYPAqISk69PrfelBEXVfgsiTy7RNP0OW91J8dFJ1TFwRj+Xyjy14QaJoPjXylOyQ5Fput0B+jxMKVVgXphO55wOeuxic5XWxsG4qxN1WqnMAQPmUKxae1JkFRL3+DfN6GOtWV+3HDMMLGv8+uVk9g+nL+3QavoLr/2YyLGLwB/dg3Tw6NZZ/FNQ4pMFpEw5DGyzq8SyMlNTqEeUjzSIMWOeFuKRGkPo2aAuB/YRVxNFTsR17za3bInul7hv0+rORGdYTwJdA0XsuUQoNKgYECL/5PMPqiS9n4FWA9pNKAavhQw3KtGJFG2p0rM0lYWNe10hrpqoWt4stIYrNKqnoSFPtN8eMEyhO2JTHSxNqL9m1nBihGUCHYEQ9sMUqgvNI9QaVPTRlrg6tqOiibk6ms+WXQ2Zs5EosYE6AOYnChDOKPHsizJ7Yi9/SetT5M/6dcF/K2meUP3phnru9FD9tp1zWQX/qpwdAGQMJNrHi/b6SE4RCBvuH+M82fLnvreu6vVXzIst8ZmPYPOss4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
