travis:
  secure:
    BINSTAR_TOKEN: cIVwp8i6caxe3WAPyqnRbcSFvjU3GCkQ4EDoagyWY7WPg30B5fFSFlXLATEB5lAtP/nxCuaW5WF0dF3lCWNjtRSPSQ7SClBdFQJjbbsD0t2P+xCC/c0G2duMdG8nqz1DgrksZXrilnwaGEsQ9y+4OEWYlqFYPAqISk69PrfelBEXVfgsiTy7RNP0OW91J8dFJ1TFwRj+Xyjy14QaJoPjXylOyQ5Fput0B+jxMKVVgXphO55wOeuxic5XWxsG4qxN1WqnMAQPmUKxae1JkFRL3+DfN6GOtWV+3HDMMLGv8+uVk9g+nL+3QavoLr/2YyLGLwB/dg3Tw6NZZ/FNQ4pMFpEw5DGyzq8SyMlNTqEeUjzSIMWOeFuKRGkPo2aAuB/YRVxNFTsR17za3bInul7hv0+rORGdYTwJdA0XsuUQoNKgYECL/5PMPqiS9n4FWA9pNKAavhQw3KtGJFG2p0rM0lYWNe10hrpqoWt4stIYrNKqnoSFPtN8eMEyhO2JTHSxNqL9m1nBihGUCHYEQ9sMUqgvNI9QaVPTRlrg6tqOiibk6ms+WXQ2Zs5EosYE6AOYnChDOKPHsizJ7Yi9/SetT5M/6dcF/K2meUP3phnru9FD9tp1zWQX/qpwdAGQMJNrHi/b6SE4RCBvuH+M82fLnvreu6vVXzIst8ZmPYPOss4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
